### PR TITLE
Cardiovascular Heart Disease Prediction | 1. Dataset Exploration

### PR DESCRIPTION
**Pull request by deedGhost**
Identifying features and labels, conversion of datatypes, finding and correcting erroneous data, less memory usage, statistical analysis

### CODE REVIEW

**Comment by deedGhost** [comment]
@SrijanShovit please check if it's correct now?

**Comment by SrijanShovit** [comment]
Corrections:
1. what's the criteria of selecting 200 and 50 as marginal values, please specify in an md cell.
2. Change the file name corresponding to the subproject.

**Comment by deedGhost** [comment]
@SrijanShovit I am done with the corrections, please check if anymore modifications required and also about the next task for the project.

**Comment by SrijanShovit** [comment]
@deedGhost approving these now, but when I assign you EDA part do check if 50,200 points align with statistical/mathematical tests used in ML.

**Review by SrijanShovit — APPROVED** [review]

**Comment by deedGhost** [comment]
Okay I'll mindful about that , thank you @SrijanShovit

**Pull request merged**
