### PR TITLE
Metabolic Syndrome Prediction | 3. Statistical Tests for Feature Importance

### PR DESCRIPTION
**Pull request by Arihant-Bhandari**
closes issue #52 Metabolic Syndrome Prediction | Statistical Tests for Feature Importance

Worked on Step 3:

* Principle Component Analysis (PCA)

* Chi-squared test

* ANOVA test

*  Independent Component Analysis (ICA)

* Permutation-related tests : RFE and Model reliance method

* Information Gain Test

### CODE REVIEW

**Comment by SrijanShovit** [comment]
Ok will check in evening once I return from office

**Comment by SrijanShovit** [comment]
1. Plot graphs for Anova and Chi-squared
2. Put XGBoost for next issue i.e. ML Based Feature Importance (this issue is for statistical)
3.  Explore Information Gain also for statistical

**Comment by Arihant-Bhandari** [comment]
Thanks for the suggestions, will update accordingly @SrijanShovit

**Comment by Arihant-Bhandari** [comment]
@SrijanShovit hi i have completed all the required tasks and edits, please review it, and if there are still changes to be done, i would be more than glad to do them; thank you for your time.

**Review by SrijanShovit — APPROVED** [review]

**Comment by SrijanShovit** [comment]
Now start working on ML based feature importance. I will create and assign issue later.

**Comment by Arihant-Bhandari** [comment]
@SrijanShovit cool i will start working on them 👍

**Pull request merged**
