### PR TITLE
Lung Cancer | Dataset Exploration

### PR DESCRIPTION
**Pull request by avii-07**
Basic dataset exploration on the Lung Cancer Dataset,
Dataset loaded, 
Features and Label,
Shape of the Dataset,
Data types and Memory Usage checked,
Basic Statistical analysis of the columns.

### CODE REVIEW

**Comment by avii-07** [comment]
@SrijanShovit  Please review the file and kindly merge it. If there are any suggestions or corrections, then let me know. 

With regards
Avi

**Comment by SrijanShovit** [comment]
Just add null check code as well.

**Comment by avii-07** [comment]
@SrijanShovit 
I have added null values code.

**Comment by avii-07** [comment]
Hi @SrijanShovit 

If this issue is completed, please merge it. 

Also, I would like to go further with this dataset, I will do preprocessing and finally will make a classifier model using different algorithms. I will find out the best model.

With regards
Avi

**Review by SrijanShovit — APPROVED** [review]

**Comment by avii-07** [comment]
@SrijanShovit 
I can see you have approved the changes. So can I go further with this dataset? or should I open it as a new issue? 
Please tell me what I need to do further.

**Comment by SrijanShovit** [comment]
Take updates about EDA, next proceed with Feature Importance part (both ML and statistical tests). You can open the issue yourself with right way of naming it.

**Comment by avii-07** [comment]
@SrijanShovit 
Thank you for assigning me the issue.
I have opened the issue.

Thank you..

**Pull request merged**
