### PR TITLE
Added Pneumonia Detection [Issue #15]

### PR DESCRIPTION
**Pull request by roysammy**
As per the [Issue #15](https://github.com/SrijanShovit/HealthLearning/issues/15) I have added the dataset and the jupyter notebook with the pre-processed and augmented data, from which other contributors can continue to contribute. Please review and merge @SrijanShovit

### CODE REVIEW

**Comment by SrijanShovit** [comment]
Have you pushed files here in this repo?

**Comment by roysammy** [comment]
Yes. You can check the PR raised

**Comment by SrijanShovit** [comment]
It shows infinite files. If the file are added in repo by you, remove all of them; upload them of kaggle and then just provide the link in readme

**Comment by SrijanShovit** [comment]
@roysammy123 any updates?

**Pull request closed without merging**
