### PR TITLE
Basic Malaria Model Workflow Completed

### PR DESCRIPTION
**Pull request by seeratfatima19**
Basic workflow completed from preprocessing to model evaluation.  Further enhancements like image augmentation and better accuracy will be started once this one is merged.

### CODE REVIEW

**Review by SrijanShovit — CHANGES_REQUESTED** [review]
Nope looks like you didn't pay attention to hyper parameter tuning stuff in that discussion.

**Comment by seeratfatima19** [comment]
As I have mentioned that it is just the basic workflow. After this, I will move towards data augmentation and also hyper parameter tuning. I just started this PR so atleast basic code will be hosted and then I can work further

**Comment by SrijanShovit** [comment]
> As I have mentioned that it is just the basic workflow. After this, I will move towards data augmentation and also hyper parameter tuning. I just started this PR so atleast basic code will be hosted and then I can work further

Ok you can continue.

**Comment by seeratfatima19** [comment]
@SrijanShovit do you intend to proceed with this PR or should we close it?

**Comment by SrijanShovit** [comment]
Will only proceed if things are aligned with requirements. Won't be merging a trial PR for the issue.

**Pull request closed without merging**
