### PR TITLE
Diabetes | feature- selection

### PR DESCRIPTION
**Pull request by Anuragsarkar12**
### Description
Performed Feature Selection
This PR does the following:
  - Compared the Chi-square values and f-statistic values for all features in different plots
  - Used  f-statistic in SelectKBest and Recursive Feature Elimination with Cross Validation to create two new datasets
  - Applied Random Forest Classifier with hyperparameter tuning on both the datasets and compared the model accuracies

### Checklist
Make sure to check off all the items before submitting. Mark with [x] if done.
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I am working on this issue under GSSOC

### CODE REVIEW

**Comment by SrijanShovit** [comment]
First do feature selection properly then jump into prediction.

**Comment by Anuragsarkar12** [comment]
Could you provide me some suggestions as to what I should use further for feature selection

**Comment by SrijanShovit** [comment]
https://github.com/SrijanShovit/HealthLearning/blob/main/Metabolic%20Syndrome%20Prediction/metabolic_syndrome_predict.ipynb

Moreover, feature selection is not what I asked for in the issue. Feature Importance is different.

**Comment by Anuragsarkar12** [comment]
Okay,I'll make the appropriate changes

**Comment by SrijanShovit** [comment]
any updates @Anuragsarkar12

**Comment by Anuragsarkar12** [comment]
I am actually out of town so I am not able to work on it, I'll return tomorrow and will make the changes within a couple of days

**Pull request closed without merging**
