### PR TITLE
StrokePrediction|ExploreDataset

### PR DESCRIPTION
**Pull request by Divyanshi1002**
#16 # Prediction | 1. Explore Dataset 

**Following changes are  made:**

- [x] 1)Load the dataset
- [x] 2)Explore and confirm features and label(s) of this dataset  3)Explore size/shape of dataset
- [x] 4)Investigate data type of features
- [x] 5)Calculate the memory usage differences
- [x] 6)Explore the statistical facts like mean, median, and percentiles of the columns

### CODE REVIEW

**Comment by SrijanShovit** [comment]
Appreciate your work @Divyanshi1002 
Just 2 things:
1. add units for memory in md cell
2. can you please add some explanation about using DT for finding missing values of BMI column

**Comment by SrijanShovit** [comment]
Moreover, please join Health Learning #general discord channel. As mentors list is out, I wanna have a central place for communication and announcements.

**Comment by Divyanshi1002** [comment]
sure, can you please provide a link to join the Health Learning channel. @SrijanShovit

**Comment by SrijanShovit** [comment]
[1238600188164177970](https://discord.com/channels/1231112132595028008/1238600188164177970) 
1. Either check this link
2. Or follow go to server > channels & roles  > browse channels > find health learning section and follow the category

**Comment by Divyanshi1002** [comment]
Please check PR for above mentioned changes.

**Comment by SrijanShovit** [comment]
Hey @Divyanshi1002 I think I am not getting you. Can you please explain a bit about the concept of using DT for checking null values or provide any links. M curious about it.

**Review by SrijanShovit — APPROVED** [review]

**Comment by Divyanshi1002** [comment]
@SrijanShovit please check for changes in the PR and i have added reference link for DT for missing value in bmi as well.
let me know if i can move further for issue #17 .

**Review by SrijanShovit — APPROVED** [review]

**Comment by SrijanShovit** [comment]
> @SrijanShovit please check for changes in the PR and i have added reference link for DT for missing value in bmi as well. let me know if i can move further for issue #17 .

yes proceed to #17 .

**Pull request merged**
