### PR TITLE
Add feature importance analysis using Chi-squared and ANOVA tests

### PR DESCRIPTION
**Pull request by MehekFatima**
Add feature importance analysis using Chi-squared and ANOVA tests

### CODE REVIEW

**Comment by MehekFatima** [comment]
Hey, I've implemented feature importance using chi-square and  ANOVA tests. I would greatly appreciate it if you could take some time to review my Pull Request. @SrijanShovit

**Comment by SrijanShovit** [comment]
I would like you to explore both these tests @MehekFatima  and decide if both or which one is applicable for which column by the fundamental definition of these tests.

**Comment by MehekFatima** [comment]
I've created a README file to address the exploration of both Chi-squared and ANOVA tests and their applicability to the columns in the dataset. The README provides a detailed explanation of the analysis performed, including the use of PCA for variance exploration and the application of Chi-squared and ANOVA tests for feature importance ranking. @SrijanShovit

**Comment by SrijanShovit** [comment]
Add the graphs please

**Comment by MehekFatima** [comment]
i have added graphs @SrijanShovit

**Comment by SrijanShovit** [comment]
Ok will check in evening once I return from office

**Review by SrijanShovit — APPROVED** [review]
Good

**Pull request merged**
