### PR TITLE
Added Readme & Input  Pipe Line  & Data PreProcessing 

### PR DESCRIPTION
**Pull request by Saksh8**
I have solved the first issue.Next Will be training the model on CNN ,

### CODE REVIEW

**Comment by SrijanShovit** [comment]
It's better you upload the files on kaggle and then add the link here. @Saksh8

**Comment by Saksh8** [comment]
I added the link of the data set on ReadMe file

**Comment by SrijanShovit** [comment]
Rejecting it, remove the images from here; just the kaggle link in readme and name the folder appropriately.

**Review by SrijanShovit — CHANGES_REQUESTED** [review]
Add a proper Acne Prediction folder and also , outputs of the notebook

**Pull request closed without merging**
