### PR TITLE
Issue: #79 Heart attack prediction model

### PR DESCRIPTION
**Pull request by jain-anshika**
# Issue: #79 
# Heart attack prediction model
The test accuracy score of Logistric Regression is  0.9016393442622951
The test accuracy score of SVM after hyper-parameter tuning is  0.9016393442622951
The test accuracy score of Gradient Boosting Classifier is  0.8688524590163934
The test accuracy score of Random Forest is  0.7868852459016393
The test accuracy score of Decision Tree is  0.7868852459016393

### CODE REVIEW

**Review by SrijanShovit — CHANGES_REQUESTED** [review]
Rejecting it. 
First start with Dataset exploration and EDA. Write your conclusions.
Later parts will be further issues. Don't just jump straight into prediction code.
Have a look at other issues and merged PRs.

**Comment by jain-anshika** [comment]
@SrijanShovit  Hey I added more comments and conclusion please check if it is okay now!!
Please tell me if there are any other changes needed.

Thank you for giving me a chance to work.

**Review by SrijanShovit — CHANGES_REQUESTED** [review]
Remove the classification part for now; I will tell how to do that in next issues and assign you.

**Comment by jain-anshika** [comment]
Do you mean I should only keep it till conclusions of EDA?

**Comment by SrijanShovit** [comment]
> Do you mean I should only keep it till conclusions of EDA?

yes, you might see for other projects also. I find it good for small steps as separate issues rather than entire project as one issue. This would help in learning and points both.

**Comment by SrijanShovit** [comment]
> > Do you mean I should only keep it till conclusions of EDA?
> 
> yes, you might see for other projects also. I find it good for small steps as separate issues rather than entire project as one issue. This would help in learning and points both.

**Review by SrijanShovit — APPROVED** [review]
Good

**Comment by SrijanShovit** [comment]
> # Issue: #79
> # Heart attack prediction model
> The test accuracy score of Logistric Regression is 0.9016393442622951 The test accuracy score of SVM after hyper-parameter tuning is 0.9016393442622951 The test accuracy score of Gradient Boosting Classifier is 0.8688524590163934 The test accuracy score of Random Forest is 0.7868852459016393 The test accuracy score of Decision Tree is 0.7868852459016393

So you see you don't have great accuracy. There can be some reasons. As we proceed with steps each with 1 issue, we can have better ideas which aspect to it to take accuracy till 98% or above.

**Pull request merged**
