### PR TITLE
Outlier Detection

### PR DESCRIPTION
**Pull request by sanketv010**
**This Pull request makes the following changes:**
* Fixes Step.2 of issue #21 

**Checklist:**
- [x] Detect Outliers.
- [x] No class label imbalance as it is a regression problem.

### CODE REVIEW

**Comment by SrijanShovit** [comment]
Ok will check in evening

**Comment by sanketv010** [comment]
> Ok will check in evening

Okay, could you assign me some other issues too?
I've been working with ML, DL and LLMs for quite a while now so i think i am suitable for level 2 and level 3 issues as well.

**Comment by SrijanShovit** [comment]
> > Ok will check in evening
> 
> Okay, could you assign me some other issues too? I've been working with ML, DL and LLMs for quite a while now so i think i am suitable for level 2 and level 3 issues as well.

How about making a Homeopathic or Ayurvedic GPT. Ayurvedic GPT can infact cover scriptures by Sushruta and other great people. Decide what you like to do, then we can proceed.

**Review by SrijanShovit — APPROVED** [review]
Good work man

**Comment by sanketv010** [comment]
> How about making a Homeopathic or Ayurvedic GPT. Ayurvedic GPT can infact cover scriptures by Sushruta and other great people. Decide what you like to do, then we can proceed.

Yes sure thing, i can do that by fine tuning a LLM on the scriptures as a custom dataset. I'll try it.

**Pull request merged**
