### PR TITLE
Stage 2

### PR DESCRIPTION
**Pull request by aditi1807**

### CODE REVIEW

**Comment by aditi1807** [comment]
Hey @SrijanShovit ,
i have completed stage 2 from my end if any changes are required kindly inform

**Comment by SrijanShovit** [comment]
Ain't you syncing up with the repo?

**Comment by aditi1807** [comment]
So sorry i didn't noticed it yet. while i did removed the complete file and then inserted it again with changes

**Comment by SrijanShovit** [comment]
> So sorry i didn't noticed it yet. while i did removed the complete file and then inserted it again with changes

😂 Do sync the repo, do git pull and then commit. Keep in mind from next time.
Moreover, do give proper names and description to the PR.

**Comment by aditi1807** [comment]
So sorry for the trouble . It's just my first time trying open source

**Comment by SrijanShovit** [comment]
> So sorry for the trouble . It's just my first time trying open source

It's ok. You learnt from this at least.

**Comment by aditi1807** [comment]
Hey @SrijanShovit ,
I have made a commit do check and let me know

**Comment by SrijanShovit** [comment]
Have a look at this: https://github.com/SrijanShovit/HealthLearning/pull/39.Try to improve similarly. You are halfway there.

**Comment by aditi1807** [comment]
I have made some changes keeping #39 in reference. could you please go through

**Comment by SrijanShovit** [comment]
You need to write the conclusion from EDA extensively what you understood.

**Comment by aditi1807** [comment]
Hey @SrijanShovit ,
Sorry for the delay.  I have tried explaining the EDA extensively from my end, kindly go through it

**Comment by SrijanShovit** [comment]
Still not convinced by your work. Try once more with #39, otherwise let's have a meet tomorrow.

**Comment by aditi1807** [comment]
@SrijanShovit from my end i have performed every step mentioned in #39 of EDA. If you are still not convinced then I am in for the meet.

**Comment by SrijanShovit** [comment]
Ok, a meeting today evening ? Just contact once me on discord or linkedin.

**Comment by aditi1807** [comment]
I have sent you a message on discord , do check it

**Pull request closed without merging**
