### PR TITLE
Metabolic Syndrome Prediction | 2. EDA

### PR DESCRIPTION
**Pull request by Arihant-Bhandari**
closes issue #20 Metabolic Syndrome Prediction | 2. EDA

worked on Step 2:

* Perform Univariate and Multivariate analysis and draw conclusions from there.

* Explore Correlation Matrix(can try different methods and search if they give the same conclusion and why)

* Check the distribution(skewness) of the columns

* Detect Outliers(don't remove)

* Detect Class Label Imbalance

additionally worked on:

* Data Encoding for categorical values

* data Imputation for NaN/Missing/NULL values

commented and wrote theory as and when required

thank you for your time reviewing this pr, if there are any suggestions i would be happy to update

### CODE REVIEW

**Comment by SrijanShovit** [comment]
superb work @Arihant-Bhandari 
Promoting this issue from level1 to level 2.

**Comment by SrijanShovit** [comment]
Next up we shall proceed with Feature importance using PCA, Anova, Chi-squared and others. i will create issues in sometime. Meanwhile, start exploring PCA. 
And please join the discord channel for this project.

**Comment by Arihant-Bhandari** [comment]
Thank you for the affirmation , means a lot to me ❤️ and thanks for the support as well.

**Comment by Arihant-Bhandari** [comment]
@SrijanShovit i cant seem to locate the discord server link to join in. could you please guide me for the same ?

**Comment by SrijanShovit** [comment]
Looks like lots to do on discord side by admin. Will ask them.

**Pull request merged**
