### PR TITLE
Added Dataset Exploration part and renamed the file

### PR DESCRIPTION
**Pull request by sanketv010**
**This Pull request makes the following changes:**
* Fixes Issue #1 

**Checklist:**
- [x] Added the exploration part into the existing PCA part and renamed the file accordingly.
- [x] Added the dataset as well.
- [x] Load the dataset.
- [x] Explore and confirm features and label(s) of this dataset.
- [x] Explore size/shape of dataset.
- [x] Investigate data type of features and labels and chose any better option for a particular column for data type if possible.
- [x] Explore the statistical facts like mean, median, x percentiles of the columns

### CODE REVIEW

**Comment by SrijanShovit** [comment]
Hi @sanketv010 You have renamed the file BodyFatPCA and put the PCA code in BodyFatPrediction.ipynb. Am I right?

**Comment by SrijanShovit** [comment]
After this,  proceed for your part of issue 20 and create a PR for you part and not entire issue.
Also join the Health learning #general channel.

**Comment by sanketv010** [comment]
> Hi @sanketv010 You have renamed the file BodyFatPCA and put the PCA code in BodyFatPrediction.ipynb. Am I right?

Yes
I did it for convenience and more organized file structure as the whole thing should be in a single notebook instead of multiple notebooks.

**Comment by sanketv010** [comment]
> After this, proceed for your part of issue 20 and create a PR for you part and not entire issue. Also join the Health learning #general channel.

Okay, is this PR in review?

**Comment by SrijanShovit** [comment]
> > Hi @sanketv010 You have renamed the file BodyFatPCA and put the PCA code in BodyFatPrediction.ipynb. Am I right?
> 
> Yes I did it for convenience and more organized file structure as the whole thing should be in a single notebook instead of multiple notebooks.

Next time leave that as it is until needed.

**Pull request merged**
