### PR TITLE
Infant Health Prediction | Explore Dataset

### PR DESCRIPTION
**Pull request by Basma2423**
I've followed the assigned instructions precisely, and they were incredibly helpful!

✅ Loaded the Dataset
✅ Explored its Shape
✅ Became familiar with the Features, their unique values, and frequencies
✅ Handled the NaN values
✅ Mapped the Categories to numbers
✅ Calculated the Memory Usage Differences
✅ Explored the Statistical Facts

The Dataset is now ready to be used. 👍

-author:Basma2423.

### CODE REVIEW

**Comment by SrijanShovit** [comment]
I can't see the jupyter file. check once.

**Comment by Basma2423** [comment]
@SrijanShovit 
Sorry.
It's uploaded now.

**Comment by Basma2423** [comment]
@SrijanShovit 
Do I need to remove the .csv file? or keep it?

**Comment by SrijanShovit** [comment]
No let it be there. I will check in evening and approve.

**Comment by SrijanShovit** [comment]
Till that time explore Statistical tests of feature importance. I will create issues when I am back from office.

**Review by SrijanShovit — APPROVED** [review]
Good work

**Comment by Basma2423** [comment]
> Good work

Thank You 🫡

**Pull request merged**
