### PR TITLE
EDA anlaysis of the dataset

### PR DESCRIPTION
**Pull request by W-ight**
Hey @SrijanShovit  as discussed in #78 issue. I have added the EDA of the dataset and a Readme file of dataset

### CODE REVIEW

**Comment by SrijanShovit** [comment]
Have a look at #39 and accordingly, write detailed conclusions from your analysis.

**Comment by SrijanShovit** [comment]
Any progress @W-ight ?

**Comment by W-ight** [comment]
hey @SrijanShovit  i have done the changes. You can review it

**Review by SrijanShovit — CHANGES_REQUESTED** [review]
Need more efforts from your side on outliers and feature distribution type and their conclusions.

What is "EDA Analysis"? Do you think this term is right?

**Comment by SrijanShovit** [comment]
Closing due to no activity here

**Pull request closed without merging**
