### PR TITLE
Step 1

### PR DESCRIPTION
**Pull request by aditi1807**
i have made some changes. do check

### CODE REVIEW

**Comment by SrijanShovit** [comment]
check if you can convert the data type of any column from float to int if there is no need of it to be in float

**Comment by SrijanShovit** [comment]
Corrections:
1. Please check the memory usage of the data before and after type conversion and I don't think, memory after removing nan is significant. If you have any facts, you can put them else remove that code.
2. Please name the commits and PR well so that it's easy for us and you as well to track what went out.

In case any help needed, feel free to ping.

**Comment by aditi1807** [comment]
Note:
1. Before the conversion the datatype of some columns were float64 but they were later converted to int64(since NAN values were also there).
2. after conversion the memory size is increasing from 3344 to 3762 for each converted columns.
should they still be converted?

**Comment by SrijanShovit** [comment]
No then there is no point. That's what I wanted.

**Pull request merged**
