### PR TITLE
Infant Health Prediction and ML Models

### PR DESCRIPTION
**Pull request by yusuf-khaan**
**Infant Health Prediction | EDA**

-> _Load the dataset_

-> _Perform Univariate and Multivariate analysis and draw conclusions from there._

-> _Explore Correlation Matrix_

-> _Check the distribution(skewness) of the columns_

-> _Detect Outliers(don't remove)_

-> _Detect Class Label Imbalance_

### CODE REVIEW

**Comment by SrijanShovit** [comment]
So, what do you think why is the performance so down? of the models?

**Comment by SrijanShovit** [comment]
Moreover, your works have lots of things but not what is intended in the issue. Read the steps again and have a thought which graphs, plots I am looking for. Once you finish this, I will eventually assign the next steps(model prediction and feature importance). But first properly focus on the assigned issue.

**Comment by yusuf-khaan** [comment]
Ok Sure @SrijanShovit ,  I will get it done in a day , Actually I have my semester exam tomorrow so i would be glad if you allow me a relaxation  for a day or two

**Comment by SrijanShovit** [comment]
You have informed me and you have exams, that's perfectly fine. No one else will hop in this issue.

**Comment by yusuf-khaan** [comment]
Thanks a lot for understanding

**Pull request closed without merging**
